In [12]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0) 
y = y/100

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivatives(x):
    return x * (1 - x)

epoch=5 
lr=0.1 

inputlayer_neurons = 2 
hiddenlayer_neurons = 3 
outputlayer_neurons = 1 

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,outputlayer_neurons))
bout=np.random.uniform(size=(1,outputlayer_neurons))

for i in range(epoch):
    hinp=np.dot(X,wh)+ bh
    hlayer = sigmoid(hinp)
    outinp=np.dot(hlayer,wout)+bout
    output = sigmoid(outinp)
    
    EO = y-output
    outgrad = sigmoid_derivatives(output)
    d_output = EO * outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = sigmoid_derivatives(hlayer)
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer.T.dot(d_output) *lr   
    wh += X.T.dot(d_hiddenlayer) *lr
    
    print ("-----------Epoch", i+1, "Starts----------")
    print("Input: \n" + str(X)) 
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" ,output)
    print ("-----------Epoch", i+1, "Ends----------\n")
        
print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)


-----------Epoch 1 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.86943323]
 [0.85540472]
 [0.8647596 ]]
-----------Epoch 1 Ends----------

-----------Epoch 2 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.86964161]
 [0.85561206]
 [0.86496808]]
-----------Epoch 2 Ends----------

-----------Epoch 3 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.86984784]
 [0.85581729]
 [0.86517442]]
-----------Epoch 3 Ends----------

-----------Epoch 4 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.87005195]
 [0.85602044]
 [0.86537864]]